import { PublicCategory } from '@/types/report';
import {
  DemoReportRecord,
  DemoMessageRecord,
  DemoEventRecord,
  DemoAttachmentRecord,
  DemoInboxItem,
} from './types';

export const SEED_CATEGORIES: PublicCategory[] = [
  { id: 'cat-akademik', name: 'Akademik & Perkuliahan', slug: 'akademik' },
  { id: 'cat-fasilitas', name: 'Sarana & Prasarana', slug: 'sarana-prasarana' },
  { id: 'cat-finansial', name: 'Keuangan & Beasiswa', slug: 'keuangan-beasiswa' },
  { id: 'cat-teknologi', name: 'Layanan IT & Sistem', slug: 'layanan-it' },
  { id: 'cat-lingkungan', name: 'Lingkungan & Ketertiban', slug: 'lingkungan-ketertiban' },
  { id: 'cat-kemahasiswaan', name: 'Kemahasiswaan & Organisasi', slug: 'kemahasiswaan' },
];

export const SEED_REPORTS: DemoReportRecord[] = [
  {
    id: 'rep-demo-001',
    reference_number: 'DEMO-2025-0001',
    access_code: 'DEMO-PASS-BARU01',
    reporter_email: 'pelapor1@example.com',
    category_id: 'cat-fasilitas',
    category_name: 'Sarana & Prasarana',
    title: 'Kerusakan Proyektor di Ruang Kuliah Umum 301',
    description:
      'Proyektor di RKU 301 mati total sejak Senin pagi sehingga kegiatan perkuliahan dan presentasi mahasiswa terganggu.',
    reporter_impact: 'Sedang',
    priority: null,
    status: 'BARU',
    first_responded_at: null,
    resolved_at: null,
    resolution_reason: null,
    resolution_next_steps: null,
    reopened_at: null,
    reopen_reason: null,
    created_at: '2025-10-01T08:30:00.000Z',
    updated_at: '2025-10-01T08:30:00.000Z',
  },
  {
    id: 'rep-demo-002',
    reference_number: 'DEMO-2025-0002',
    access_code: 'DEMO-PASS-TINJAU02',
    reporter_email: 'pelapor2@example.com',
    category_id: 'cat-finansial',
    category_name: 'Keuangan & Beasiswa',
    title: 'Keterlambatan Pencairan Dana Beasiswa Prestasi Semester Ganjil',
    description:
      'Dana bantuan beasiswa prestasi semester ganjil bagi 15 mahasiswa perwakilan belum masuk ke rekening tabungan hingga akhir bulan jadwal pencairan resmi.',
    reporter_impact: 'Tinggi',
    priority: 'P3',
    status: 'DITINJAU',
    first_responded_at: '2025-09-29T10:05:00.000Z',
    resolved_at: null,
    resolution_reason: null,
    resolution_next_steps: null,
    reopened_at: null,
    reopen_reason: null,
    created_at: '2025-09-28T09:15:00.000Z',
    updated_at: '2025-09-29T10:00:00.000Z',
  },
  {
    id: 'rep-demo-003',
    reference_number: 'DEMO-2025-0003',
    access_code: 'DEMO-PASS-PROSES03',
    reporter_email: 'pelapor3@example.com',
    category_id: 'cat-teknologi',
    category_name: 'Layanan IT & Sistem',
    title: 'Gangguan Akses Wi-Fi Kampus di Gedung Perpustakaan Pusat Lantai 2',
    description:
      'Access Point di lantai 2 perpustakaan pusat sering mengalami putus sambung (intermittent connection) sejak kemarin sore, menghambat mahasiswa mengakses jurnal.',
    reporter_impact: 'Sedang',
    priority: 'P2',
    status: 'DIPROSES',
    first_responded_at: '2025-09-26T14:10:00.000Z',
    resolved_at: null,
    resolution_reason: null,
    resolution_next_steps: null,
    reopened_at: null,
    reopen_reason: null,
    created_at: '2025-09-25T11:00:00.000Z',
    updated_at: '2025-09-26T14:00:00.000Z',
  },
  {
    id: 'rep-demo-004',
    reference_number: 'DEMO-2025-0004',
    access_code: 'DEMO-PASS-TUNGGU04',
    reporter_email: 'pelapor4@example.com',
    category_id: 'cat-akademik',
    category_name: 'Akademik & Perkuliahan',
    title: 'Permohonan Klarifikasi Jadwal Ujian Susulan Mata Kuliah Kalkulus',
    description:
      'Saya tidak dapat mengikuti UTS Kalkulus karena rawat inap di rumah sakit dan ingin mengonfirmasi kelengkapan berkas untuk penjadwalan ujian susulan.',
    reporter_impact: 'Tinggi',
    priority: 'P3',
    status: 'MENUNGGU_BALASAN_PELAPOR',
    first_responded_at: '2025-09-23T11:35:00.000Z',
    resolved_at: null,
    resolution_reason: null,
    resolution_next_steps: null,
    reopened_at: null,
    reopen_reason: null,
    created_at: '2025-09-22T08:00:00.000Z',
    updated_at: '2025-09-23T11:30:00.000Z',
  },
  {
    id: 'rep-demo-005',
    reference_number: 'DEMO-2025-0005',
    access_code: 'DEMO-PASS-SELESAI05',
    reporter_email: 'pelapor5@example.com',
    category_id: 'cat-fasilitas',
    category_name: 'Sarana & Prasarana',
    title: 'Perbaikan Wastafel Rusak di Toilet Pria Gedung B Lantai 1',
    description:
      'Kran wastafel bocor dan pipa pembuangan air tersumbat di toilet pria gedung B lantai 1, menyebabkan genangan di lantai.',
    reporter_impact: 'Rendah',
    priority: 'P1',
    status: 'SELESAI',
    first_responded_at: '2025-09-21T08:00:00.000Z',
    resolved_at: '2025-09-21T16:00:00.000Z',
    resolution_reason:
      'Pipa saluran air dan kran wastafel telah diganti oleh teknisi fasilitas. Saluran air lancar dan area telah dibersihkan.',
    resolution_next_steps:
      'Pemeliharaan berkala toilet gedung B dijadwalkan setiap pekan oleh unit pengelola sarana.',
    reopened_at: null,
    reopen_reason: null,
    created_at: '2025-09-20T09:00:00.000Z',
    updated_at: '2025-09-21T16:00:00.000Z',
  },
  {
    id: 'rep-demo-006',
    reference_number: 'DEMO-2025-0006',
    access_code: 'DEMO-PASS-LAMPIR06',
    reporter_email: 'pelapor6@example.com',
    category_id: 'cat-lingkungan',
    category_name: 'Lingkungan & Ketertiban',
    title: 'Usulan Penambahan Tempat Sampah Pemilahan Organik di Area Kantin',
    description:
      'Untuk mendukung inisiatif kampus ramah lingkungan, mahasiswa mengusulkan penyediaan tempat sampah terpilah (organik, anorganik, residu) di sudut barat kantin utama.',
    reporter_impact: 'Sedang',
    priority: 'P3',
    status: 'DIPROSES',
    first_responded_at: '2025-09-19T13:10:00.000Z',
    resolved_at: null,
    resolution_reason: null,
    resolution_next_steps: null,
    reopened_at: null,
    reopen_reason: null,
    created_at: '2025-09-18T10:00:00.000Z',
    updated_at: '2025-09-19T13:00:00.000Z',
  },
];

export const SEED_MESSAGES: DemoMessageRecord[] = [
  {
    id: 'msg-demo-002-1',
    report_id: 'rep-demo-002',
    sender_type: 'ADMIN',
    admin_name: 'Admin Kemahasiswaan',
    visibility: 'PUBLIC_TO_REPORTER',
    message:
      'Laporan Anda sedang kami verifikasi bersama bagian keuangan rektorat. Mohon menunggu pembaruan dalam 2 hari kerja.',
    created_at: '2025-09-29T10:05:00.000Z',
  },
  {
    id: 'msg-demo-003-1',
    report_id: 'rep-demo-003',
    sender_type: 'ADMIN',
    admin_name: 'Helpdesk IT',
    visibility: 'PUBLIC_TO_REPORTER',
    message:
      'Tim teknis jaringan telah menerima informasi ini dan sedang memeriksa unit switch distribusi di lantai 2 gedung perpustakaan.',
    created_at: '2025-09-26T14:10:00.000Z',
  },
  {
    id: 'msg-demo-004-1',
    report_id: 'rep-demo-004',
    sender_type: 'ADMIN',
    admin_name: 'Sekretariat Jurusan',
    visibility: 'PUBLIC_TO_REPORTER',
    message:
      'Mohon sertakan NIM, kelas paralel, dan nomor surat keterangan dokter agar kami dapat mengajukan permohonan ke koordinator mata kuliah.',
    created_at: '2025-09-23T11:35:00.000Z',
  },
  {
    id: 'msg-demo-005-1',
    report_id: 'rep-demo-005',
    sender_type: 'ADMIN',
    admin_name: 'Bagian Sarpras',
    visibility: 'PUBLIC_TO_REPORTER',
    message:
      'Teknisi sarana telah menyelesaikan perbaikan kran dan pembersihan pipa pembuangan toilet pria lantai 1.',
    created_at: '2025-09-21T16:05:00.000Z',
  },
  {
    id: 'msg-demo-006-1',
    report_id: 'rep-demo-006',
    sender_type: 'ADMIN',
    admin_name: 'Unit K3L Kampus',
    visibility: 'PUBLIC_TO_REPORTER',
    message:
      'Denah usulan telah kami terima. Usulan ini akan dibahas pada rapat koordinasi fasilitas kantin pekan depan.',
    created_at: '2025-09-19T13:10:00.000Z',
  },
];

export const SEED_EVENTS: DemoEventRecord[] = [
  // rep-demo-001
  {
    id: 'ev-demo-001-1',
    report_id: 'rep-demo-001',
    actor_type: 'SYSTEM',
    event_type: 'LAPORAN_DIBUAT',
    new_status: 'BARU',
    created_at: '2025-10-01T08:30:00.000Z',
  },
  // rep-demo-002
  {
    id: 'ev-demo-002-1',
    report_id: 'rep-demo-002',
    actor_type: 'SYSTEM',
    event_type: 'LAPORAN_DIBUAT',
    new_status: 'BARU',
    created_at: '2025-09-28T09:15:00.000Z',
  },
  {
    id: 'ev-demo-002-2',
    report_id: 'rep-demo-002',
    actor_type: 'ADMIN',
    event_type: 'STATUS_DIUBAH',
    old_status: 'BARU',
    new_status: 'DITINJAU',
    old_priority: undefined,
    new_priority: 'P3',
    created_at: '2025-09-29T10:00:00.000Z',
  },
  // rep-demo-003
  {
    id: 'ev-demo-003-1',
    report_id: 'rep-demo-003',
    actor_type: 'SYSTEM',
    event_type: 'LAPORAN_DIBUAT',
    new_status: 'BARU',
    created_at: '2025-09-25T11:00:00.000Z',
  },
  {
    id: 'ev-demo-003-2',
    report_id: 'rep-demo-003',
    actor_type: 'ADMIN',
    event_type: 'STATUS_DIUBAH',
    old_status: 'BARU',
    new_status: 'DITINJAU',
    created_at: '2025-09-26T08:00:00.000Z',
  },
  {
    id: 'ev-demo-003-3',
    report_id: 'rep-demo-003',
    actor_type: 'ADMIN',
    event_type: 'STATUS_DIUBAH',
    old_status: 'DITINJAU',
    new_status: 'DIPROSES',
    old_priority: undefined,
    new_priority: 'P2',
    created_at: '2025-09-26T14:00:00.000Z',
  },
  // rep-demo-004
  {
    id: 'ev-demo-004-1',
    report_id: 'rep-demo-004',
    actor_type: 'SYSTEM',
    event_type: 'LAPORAN_DIBUAT',
    new_status: 'BARU',
    created_at: '2025-09-22T08:00:00.000Z',
  },
  {
    id: 'ev-demo-004-2',
    report_id: 'rep-demo-004',
    actor_type: 'ADMIN',
    event_type: 'STATUS_DIUBAH',
    old_status: 'BARU',
    new_status: 'DITINJAU',
    created_at: '2025-09-22T13:00:00.000Z',
  },
  {
    id: 'ev-demo-004-3',
    report_id: 'rep-demo-004',
    actor_type: 'ADMIN',
    event_type: 'STATUS_DIUBAH',
    old_status: 'DITINJAU',
    new_status: 'MENUNGGU_BALASAN_PELAPOR',
    reason: 'Menunggu kelengkapan dokumen pendukung',
    created_at: '2025-09-23T11:30:00.000Z',
  },
  // rep-demo-005
  {
    id: 'ev-demo-005-1',
    report_id: 'rep-demo-005',
    actor_type: 'SYSTEM',
    event_type: 'LAPORAN_DIBUAT',
    new_status: 'BARU',
    created_at: '2025-09-20T09:00:00.000Z',
  },
  {
    id: 'ev-demo-005-2',
    report_id: 'rep-demo-005',
    actor_type: 'ADMIN',
    event_type: 'STATUS_DIUBAH',
    old_status: 'BARU',
    new_status: 'DITINJAU',
    created_at: '2025-09-20T10:00:00.000Z',
  },
  {
    id: 'ev-demo-005-3',
    report_id: 'rep-demo-005',
    actor_type: 'ADMIN',
    event_type: 'STATUS_DIUBAH',
    old_status: 'DITINJAU',
    new_status: 'DIPROSES',
    created_at: '2025-09-21T08:00:00.000Z',
  },
  {
    id: 'ev-demo-005-4',
    report_id: 'rep-demo-005',
    actor_type: 'ADMIN',
    event_type: 'STATUS_DIUBAH',
    old_status: 'DIPROSES',
    new_status: 'SELESAI',
    reason: 'Perbaikan wastafel selesai dilakukan.',
    created_at: '2025-09-21T16:00:00.000Z',
  },
  // rep-demo-006
  {
    id: 'ev-demo-006-1',
    report_id: 'rep-demo-006',
    actor_type: 'SYSTEM',
    event_type: 'LAPORAN_DIBUAT',
    new_status: 'BARU',
    created_at: '2025-09-18T10:00:00.000Z',
  },
  {
    id: 'ev-demo-006-2',
    report_id: 'rep-demo-006',
    actor_type: 'ADMIN',
    event_type: 'STATUS_DIUBAH',
    old_status: 'BARU',
    new_status: 'DITINJAU',
    created_at: '2025-09-18T14:00:00.000Z',
  },
  {
    id: 'ev-demo-006-3',
    report_id: 'rep-demo-006',
    actor_type: 'ADMIN',
    event_type: 'STATUS_DIUBAH',
    old_status: 'DITINJAU',
    new_status: 'DIPROSES',
    created_at: '2025-09-19T13:00:00.000Z',
  },
];

export function createSeedAttachments(): DemoAttachmentRecord[] {
  const samplePdfBytes = new Uint8Array([
    0x25, 0x50, 0x44, 0x46, 0x2d, 0x31, 0x2e, 0x34, 0x0a, 0x25, 0xd0, 0xd4, 0xc5, 0xd8, 0x0a,
  ]);
  const blob = new Blob([samplePdfBytes], { type: 'application/pdf' });

  return [
    {
      id: 'att-demo-006-1',
      report_id: 'rep-demo-006',
      original_filename: 'denah-usulan-kantin.pdf',
      filename: 'denah-usulan-kantin.pdf',
      file_size_bytes: samplePdfBytes.byteLength,
      content_type: 'application/pdf',
      blob,
      created_at: '2025-09-18T10:00:00.000Z',
    },
  ];
}

export const SEED_INBOX_ITEMS: DemoInboxItem[] = [
  {
    id: 'inbox-seed-001',
    email: 'pelapor4@example.com',
    subject: '[Simulasi Demo] Kode Akses Laporan Anda: DEMO-2025-0004',
    body:
      'Halo Pelapor, laporan Anda mengenai "Permohonan Klarifikasi Jadwal Ujian Susulan" telah tercatat di sistem demo lokal. Kode akses rahasia Anda adalah: DEMO-PASS-TUNGGU04. Simpan kode ini untuk melihat perkembangan dan membalas pesan tim pengelola.',
    created_at: '2025-09-22T08:00:00.000Z',
  },
  {
    id: 'inbox-seed-002',
    email: 'pelapor1@example.com',
    subject: '[Simulasi Demo] Kode Akses Laporan Anda: DEMO-2025-0001',
    body:
      'Halo Pelapor, laporan Anda mengenai "Kerusakan Proyektor di Ruang Kuliah Umum 301" telah tercatat di sistem demo lokal. Kode akses rahasia Anda adalah: DEMO-PASS-BARU01.',
    created_at: '2025-10-01T08:30:00.000Z',
  },
];
